ALTER TABLE users
  ADD COLUMN password VARCHAR(100),
  ADD COLUMN balance INTEGER DEFAULT 0,
  ADD COLUMN rating FLOAT DEFAULT 0.0,
  ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN birth_date DATE,
  ADD COLUMN married BOOLEAN DEFAULT false;

ALTER TABLE users
  ALTER COLUMN password SET NOT NULL;
